### PR TITLE
fix: avoid DeprecationWarning 'werkzeug.urls.url_decode' is deprecated

### LINKED ISSUE #744: address deprecations from Werkzeug 2.3
**Describe the bug**
https://github.com/maxcountryman/flask-login/blob/b30758205211c3af4ac6a41601aee17f6aa45f64/src/flask_login/utils.py#L15 is deprecated and will be removed in Werkzeug 2.4

```
/.venv/lib/python3.9/site-packages/flask_login/utils.py:130: DeprecationWarning: 'werkzeug.urls.url_encode' is deprecated and will be removed in Werkzeug 2.4. Use 'urllib.parse.urlencode' instead.
    netloc=netloc, query=url_encode(md, sort=True)
```

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by miettal**
close #744

### CODE REVIEW

**Comment by miettal** [comment]
some tests failed because of #743.
if #743 is merged, I'll rebase main.

**Comment by sr-verde** [comment]
Hey nice, would like to see that merged.

**Comment by miettal** [comment]
Yesterday werkzeug==3.0.0 was released and dropped werkzeug.urls.
So form yesterday, combination of flask-login and werkzeug>=3.0.0 will be not work.

**Comment by davidism** [comment]
I'm on vacation right now. A maintainer will work on this when they are available. We are aware of it.

**Review by alanhamlett — APPROVED** [review]

**Pull request merged**
