### PR TITLE
Release as a universal wheel

### PR DESCRIPTION
**Pull request by adamchainz**
By releasing as a [Python wheel](http://pythonwheels.com/) as well as a source distribution, you can speed up end user’s installs. After merging this command, to release you just need to run `python setup.py clean sdist bdist_wheel upload`.

### CODE REVIEW

**Comment by alanhamlett** [comment]
@adamchainz tests were fixed with #310. Can you rebase your fork to fix tests?

Here are the commands you can run in your fork directory:
```
git remote add upstream git@github.com:maxcountryman/flask-login.git
git fetch upstream
git rebase upstream/master
git push
```

**Comment by adamchainz** [comment]
Done

**Comment by alanhamlett** [comment]
Thanks!

**Comment by adamchainz** [comment]
🎉 🎈 🎂 🎁 💝 

:cheese:

**Pull request merged**
