### PR TITLE
python>=3.7 supported, drop 3.5 and 3.6

### PR DESCRIPTION
**Pull request by davidism**
Drop Python versions that have reached end of life.

### CODE REVIEW

**Comment by davidism** [comment]
@maxcountryman Unfortunately, the 3.5 and 3.6 test envs are marked as "required", and I don't have enough permissions to change that. Can you add me to the maintainers for this repo?

I'll just keep some fake envs around in the mean time.

**Comment by maxcountryman** [comment]
@davidism it seems I can only add people as collaborators--is there another way to give you additional rights?

**Comment by maxcountryman** [comment]
I removed the status check requirements for now. Kind of unfortunate I can't just let you and other collaborators configure that.

**Comment by davidism** [comment]
Hmm, maybe it works different for orgs, for Flask I have the option to choose "Maintain" or "Admin".

Well, if you're up for it, I've been slowly working on a new Pallets-Eco org for community maintained projects: https://github.com/pallets-eco. I was eventually going to ask you about it anyway.

Me and other Pallets members have access, can add more community members, and we'll be working out how to allow community maintenance while allowing a trusted group to actually make releases. You would of course still have full ownership as well, but I understand it's a big thing to spring on you.

**Comment by davidism** [comment]
If you want to discuss that elsewhere, you can message me on Twitter https://twitter.com/davidism or the Pallets Discord https://discord.gg/pallets.

**Pull request merged**
