### PR TITLE
Drop Python 2.7 support

### LINKED ISSUE #508: Drop Python 2 support?
As many of us are aware, Python 2 has officially been retired. While there are no doubt plenty of projects that haven't migrated, there's never been a better time to call it.

Any opposition to removing Python 2 from our test suite and no longer officially supporting it in this project?

### PR DESCRIPTION
**Pull request by le717**
Fixes #508.

This removes all support for and references to Python 2.7, including in the test matrix. Most changes were performed through running `2to3` but some work was performed manually, such as `import`s and removing the `_compat` module. Running `make clean` reports all is well.

### CODE REVIEW

**Comment by le717** [comment]
It looks like the tests are failing because of a missing secret key required for GitHub Actions.

**Comment by le717** [comment]
@maxcountryman Is there any way you can take a look at this? There were some improvements I wanted to contribute to this (_very depended upon_) library and this is something that is needed to be done anyway.

**Comment by maxcountryman** [comment]
I think we can merge this as-is for now.

**Comment by maxcountryman** [comment]
Why don't you rebase and force push?

Tests seem to be passing for other recent PRs, e.g. Dependabot.

**Comment by le717** [comment]
Rebased and force pushed. Checks aren't running because I'm a first-time contributor so you need to approve running the workflow.

**Comment by maxcountryman** [comment]
Seems like it's still failing. I added a change to the coveralls invocation which seems to be working on `main` (I hope it's working for contributor PRs too).

**Comment by le717** [comment]
I just pulled that change into this PR so hopefully it'll pass now :)

**Comment by maxcountryman** [comment]
Hm okay looks like a new error now?

**Comment by le717** [comment]
It looks like `GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}` needs to be added to the `env` section of `tests.yaml`. I've never used GH Actions so I don't know where that token would be obtained for coveralls to access it. Maybe it automagically exists?

**Comment by maxcountryman** [comment]
It's provided by Github. I added that but I don't think that's fixing the issue. For some reason this worked fine for my PR and merge into `main`.

**Comment by le717** [comment]
Now it's failing with a 422 to the coveralls API. I have no idea what is going on. Do you want me to flatten this back into a single commit again and maybe you can merge it without the checks passing (if you can)? Or perhaps maybe opening a new PR would help (somehow???)?

**Comment by maxcountryman** [comment]
I'm stumped.

Maybe there's some hints here? --> https://stackoverflow.com/questions/65692711/using-python-coveralls-from-github-actions-returns-could-not-submit-coverage-4

**Comment by le717** [comment]
I might have found it.

1. https://github.com/TheKevJames/coveralls-python/issues/252#issuecomment-828781665
> However, like I said, Coveralls does not recommend using COVERALLS_REPO_TOKEN when using Github Actions. We recommend using ${{ secrets.GITHUB_TOKEN }} when using service_name: github.

2. The `run: coveralls --service=github` had `github` spelled as `gihtub`. Maybe it'll work _now_ 😅

**Comment by maxcountryman** [comment]
Nice catch! Giving it another go.

**Comment by maxcountryman** [comment]
Progress. It seems like 3.5 can't find a dep tho.

**Comment by le717** [comment]
I'm pretty sure Python 3.5 is EOL and Flask 2.0 dropped support for it. I can either add a 3.5 dep or drop it from the test matrix (and effectively from support too).

**Comment by le717** [comment]
OK, so pytest 6.2.0+ only supports Python 3.6+ and there's enough changes (and I don't know enough) from 6.1 that I don't know if it's possible to run the existing tests on pytest 6.1.

**Comment by le717** [comment]
OK! It finally all worked! It only required all day and somehow wrecking the commit history. 😅 Let me close this and issue a new PR with a clean history. :)

**Pull request closed without merging**
