### PR TITLE
refactor into module folder

### PR DESCRIPTION
**Pull request by alanhamlett**

### CODE REVIEW

**Comment by alanhamlett** [comment]
@maxcountryman since this touches all files probably best to merge this before any other pull requests?

**Comment by maxcountryman** [comment]
Yeah, I'm wondering if we should hold off on this for now?

**Comment by alanhamlett** [comment]
Thinking this should be postponed for a major release?

**Comment by maxcountryman** [comment]
Yeah, that seems reasonable. I'd like to roll out the current backlog and then circle back to this.

**Comment by alanhamlett** [comment]
Ok, let me know when you're ready in future and I'll resolve any merge conflicts or just do it over.

**Comment by maxcountryman** [comment]
Okay, sorry for the delay! I've been meaning to get to a release soon, but haven't had much time recently.

**Comment by maxcountryman** [comment]
@alanhamlett I just released `0.3.0` to PyPI.

**Comment by alanhamlett** [comment]
Closing in favor of #270

**Pull request closed without merging**
