### PR TITLE
Add pypi release github action workflow (#557)

### LINKED ISSUE #557: Contributors welcome: Automated PyPI releases
It's now possible to author new PyPI releases via a GitHub Action workflow. This reduces friction to actually publishing a release (quite a lot on my end, where I often don't have a working Python dev environment).

If anyone is interested in taking this on, you could likely use [the Flask-SeaSurf workflow])(https://github.com/maxcountryman/flask-seasurf/blob/master/.github/workflows/publish-release.yml) as a blueprint.

### PR DESCRIPTION
**Pull request by Demetriex**
closes #557

### CODE REVIEW

**Comment by nnvai47** [comment]
I'm trying to get access to the `REMEMBER_COOKIE_SAMESITE` config in https://github.com/maxcountryman/flask-login/pull/453, and I think a release with that is blocked on the present PR. Is this waiting on the tests being fixed?

**Comment by nnvai47** [comment]
@maxcountryman this appears to be up to date and passing all tests.

**Comment by jonasps** [comment]
Hi, @maxcountryman is this PR what is needed for a new release or are there more things needed?
If so could I help with anything?

**Comment by Demetriex** [comment]
@jonasps, @maxcountryman already made a commit that does the auto release on pypi.

https://github.com/maxcountryman/flask-login/blob/main/.github/workflows/publish-release.yml

**Comment by jonasps** [comment]
@Demetriex Can this also be closed? https://github.com/maxcountryman/flask-login/issues/557#issuecomment-1003377488

**Pull request closed without merging**
