### PR TITLE
update project metadata

### PR DESCRIPTION
**Pull request by davidism**
* switch to setup.cfg for packaging metadata
* use latest sphinx build script
* move tests to a directory
* render changes as markdown on github
* add editorconfig
* update gitignore

To do, once I can merge without squashing:

* move to src directory
* add pre-commit, apply black and other code style consistency tools

### CODE REVIEW

**Comment by davidism** [comment]
@maxcountryman can you enable the other two commit styles besides "squash and merge"? GitHub recently added support for [`.git-blame-ignore-revs`](https://docs.github.com/en/repositories/working-with-files/using-files/viewing-a-file#ignore-commits-in-the-blame-view), which is useful for ignoring style changes, but I can't set that if squash changes the commit id.

**Comment by davidism** [comment]
These are the last changes to modernize the code base, then I'll try using the automated release workflow to tag 0.6.0.

**Comment by davidism** [comment]
I'll merge this as-is and make the other changes in separate PRs, then I can make that file with the resulting commit ids.

**Comment by maxcountryman** [comment]
Yep I'll update the settings.

**Pull request merged**
