### PR TITLE
Updated dead link

### PR DESCRIPTION
**Pull request by makeworld-the-better-one**

### CODE REVIEW

**Comment by maxcountryman** [comment]
Thanks!

**Comment by davidism** [comment]
@maxcountryman pr #444 discussed this too

> That particular snippet is ok, I think. But the quality, up-to-date-ness, and long term helpfulness of the snippet repository overall was not good, and there had been a giant warning on it for years.

> I'd much rather see that snippet brought into Flask-Login, either in code or in docs, rather than keeping that site alive by linking to the archive.

**Comment by maxcountryman** [comment]
@davidism hm maybe we should remove it instead.

**Comment by davidism** [comment]
I think adding the snippet to the docs is fine. It might even be useful to add as a function so we can test and improve it.

**Comment by makeworld-the-better-one** [comment]
I agree, I was just making a quick fix. Adding it to the docs or even better, the lib itself, would be great to see.

**Pull request merged**
