### PR TITLE
Replace safe_str_cmp with hmac.compare_digest

### PR DESCRIPTION
**Pull request by nickjj**
This resolves issue https://github.com/maxcountryman/flask-login/issues/584.

### CODE REVIEW

**Comment by nickjj** [comment]
Looks like CI is failing because of errors like this:

```
Running on Github Actions but GITHUB_TOKEN is not set.
Add "env: GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}" to your step config
```

Link: https://github.com/maxcountryman/flask-login/pull/585/checks?check_run_id=2567007897#step:9:8

**Comment by le717** [comment]
@nickjj If you will rebase this PR with the latest changes, the checks should pass now. :)

**Comment by nickjj** [comment]
I think that should do it.

**Comment by maxcountryman** [comment]
Fantastic. Thank you!

**Pull request merged**
