### PR TITLE
Add option to store 'next' in session rather than the url.

### PR DESCRIPTION
**Pull request by HoustonFortney**
I'm a fan of "pretty" urls and would prefer that it just says www.example.com/login and not a long parameter string. This was already requested in issue #123.

I added a config variable `USE_SESSION_FOR_NEXT` which defaults to false, but when set to true engages the feature.

I had to do some minor refactoring of utils to avoid duplication.

I added a test and updated the docs.

### CODE REVIEW

**Comment by alanhamlett** [comment]
Looks good to me, except for the 2 lines which are longer than 80 chars which causes tests to fail:
```
flask_login/login_manager.py line 167
flask_login/login_manager.py line 168
```

**Comment by alanhamlett** [comment]
Also, it would be cleaner to squash these commits into one commit. The easiest way to do this is:

```
git reset f8eb24eaf8f1cea87d354d1377240cb3f8f69aaf
git commit -a
```

That will re-commit all your changes under one commit and prompt you for the new commit message.

**Comment by HoustonFortney** [comment]
@alanhamlett I fixed the lines and then squashed the commits.

**Comment by HoustonFortney** [comment]
Wait... Should I put "next" in the SESSION_KEYS config variable?

**Comment by alanhamlett** [comment]
> Should I put "next" in the SESSION_KEYS config variable?

Yes, good catch.

**Comment by HoustonFortney** [comment]
I added the key to SESSION_KEYS and re-squashed.

**Comment by alanhamlett** [comment]
Thank you!

**Comment by HoustonFortney** [comment]
#123 can probably be closed.

**Comment by maxcountryman** [comment]
Nice work 👍

**Comment by lipis** [comment]
Can we make a new release with this fix?!

**Comment by coreybrett** [comment]
If this feature is used, is validateing the value of the next parameter still necssasary?

**Comment by alanhamlett** [comment]
It doesn't hurt to always validate urls before redirecting, but it would only be required if user input can change the next url somehow. I would always validate urls before redirecting, since it's a security risk.

**Pull request merged**
