### PR TITLE
apply various style tools for consistency

### PR DESCRIPTION
**Pull request by davidism**
This adds a [pre-commit](https://pre-commit.com/) configuration with the same style tools and configuration used by Flask. Contributors can enable pre-commit locally with `pre-commit install`, but it will also run in CI. For now, I used the pre-commit [action](https://github.com/pre-commit/action), but @maxcountryman can enable the [pre-commit.ci](https://pre-commit.ci/) service, which has the additional benefits of auto-updating pins and auto-fixing PRs.

* [pyupgrade](https://github.com/asottile/pyupgrade) helps ensure that we're using modern Python idioms and capabilities based on the minimum supported Python version.
* [reorder_python_imports](https://github.com/asottile/reorder_python_imports) applies a consistent order and style to imports so that changes are easy to diff in future commits.
* [black](https://black.readthedocs.io/en/stable/) applies a consistent code style.
* [flake8](https://flake8.pycqa.org/en/latest/), along with the [bugbear](https://github.com/PyCQA/flake8-bugbear) and [implicit-str-concat](https://github.com/flake8-implicit-str-concat/flake8-implicit-str-concat) plugins, lints common code issues that can't be fixed automatically with the other tools.
* [pip-compile-multi](https://pip-compile-multi.readthedocs.io/en/latest/) checks that any changes to requirements input files were recompiled to txt files.
* pre-commit comes with some simple hooks for removing trailing space, removing UTF-8 BOM, and ensuring files end with newlines.

Since these, especially pyupgrade and black, change pretty much every line of code, I've added a `.git-blame-ignore-revs` file. [GitHub will ignore listed commits in its blame view.](https://docs.github.com/en/repositories/working-with-files/using-files/viewing-a-file#ignore-commits-in-the-blame-view) Git can be configured to do this as well with `git config --global blame.ignoreRevsFile .git-blame-ignore-revs`.

### CODE REVIEW

**Comment by davidism** [comment]
@maxcountryman I can merge this once you enable the "merge commit" option.

**Comment by maxcountryman** [comment]
@davidism I removed branch protection entirely.

**Comment by davidism** [comment]
I was referring to these options:
Screenshot_20220329_143129

**Comment by maxcountryman** [comment]
@davidism all the merge options should be enabled now.

**Pull request merged**
