### PR TITLE
use current_app.ensure_sync for asyncio compatibility

### PR DESCRIPTION
**Pull request by jonasps**
Using current_app.ensure_sync as proposed here https://github.com/maxcountryman/flask-login/issues/589

### CODE REVIEW

**Comment by maxcountryman** [comment]
I have to admit I'm probably not the right person to know if this should work the way we hope given that I'm a bit out of touch with the Flask async stuff.

Would it be possible to write a test that can help us demonstrate the issue and that this fixes it?

**Comment by jonasps** [comment]
> Would it be possible to write a test that can help us demonstrate the issue and that this fixes it?

Sure, I will add some in test_login.py, will have time this weekend.

**Comment by jonasps** [comment]
I believe this is ready to review now.

**Comment by maxcountryman** [comment]
Thank you!

**Pull request merged**
