### PR TITLE
add a session block cache to improve protection

### PR DESCRIPTION
**Pull request by dpgaspar**
This PR proposes a new feature to improve session protection.

Currently, the `SESSION_PROTECTION` setting supports the `strong` option, which utilizes a secure hash of the IP address and user agent. While this provides a good level of security, it may not be able to protect against all scenarios involving stolen session cookies. For instance, it may not be effective when multiple users, including the attacker, are behind a proxy or NAT gateway. Additionally, there are situations where a strong session protection is necessary or preferred, but it cannot be implemented due to automated authentication mechanisms.

Additionally, security audits typically expect a session cookie to be invalidated once a user logs out.

This proposal uses a non opinionated centralized cache to store invalid sessions. This cache is configured using a new config option `SESSION_BLOCK_CACHE` that expects an instantiated class that implements `get` and `set`.
(on python > 3.8 would be nice to set a type `Protocol` for this)

### CODE REVIEW

**Comment by dpgaspar** [comment]
@maxcountryman @davidism gentle ping :)

Also it seems CI tests for 3.9, 3.8 are falling probably due to Wekzeug/Flask versions

**Comment by dpgaspar** [comment]
@maxcountryman @davidism would be great if you could review, I've rebased and CI is green now

**Comment by davidism** [comment]
Sorry @dpgaspar, I have very little time to work on Flask-Login specifically, and don't really understand this change. I'm not clear if it's in scope or the correct solution to the problem described. I probably won't have a chance to get this in any time soon. I'm happy to chat about maintenance more in the [Pallets Discord](https://discord.gg/pallets).

**Comment by dpgaspar** [comment]
@davidism 

The idea behind this PR is:

- On login we set the session with a new attribute named `_serial` this serves as a unique id, this will be useful for flask-login to uniquely identify a session.
- On logout we set a cache key with the session `_serial`, any requests made with a session cookie with this `serial` will be denied.

This protects users from session hijacking when users logout

**Comment by dpgaspar** [comment]
Closing this PR, opted by implementing optional server side sessions on downstream projects

**Pull request closed without merging**
